version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
    cooldown:
      default-days: 7
